name: Upload to Cloudflare R2  
  
on:  
  push:  
    branches:  
      - main  # 触发工作流的分支，可以根据需要修改  
  
jobs:  
  upload:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  
  
    - name: Install zip  
      run: sudo apt-get install -y zip  
  
    - name: Compress code  
      run: zip -r code.zip .  
  
    - name: Install AWS CLI  
      run: |  
        sudo apt-get update  
        sudo apt-get install -y awscli  
  
    - name: Configure AWS CLI  
      run: |  
        aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}  
        aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}  
        aws configure set default.region us-east-1  # 根据需要修改区域  
  
    - name: Upload to Cloudflare R2  
      run: |  
        aws s3 cp code.zip s3://lq-test/code.zip --endpoint-url=https://c7c9a6c6ea868691fb80007dfdbb44a9.r2.cloudflarestorage.com 
  
